name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    # run every day at noon UTC
    - cron: "0 12 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |-
          npm install
      - name: run it
        run: |-
          node index.js json > data/today.json
          cp data/history.json data/history.json.tmp
          jq '. += [input]' data/history.json.tmp data/today.json > data/history.json
          rm data/history.json.tmp
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
